### ISSUE TITLE
Trouble Shooting (1) Run jasypt 복호화 환경변수 미지정 에러

### ISSUE THREAD

**Issue by chaSunil** [chaSunil/troubleShooting#2]
**프로젝트 명 : final project**

**담당 파트 : 주문 및 결제**

**작성자 명 :**  차선일

**작성 일자 : 2024-09-12**

**Comment by chaSunil** [comment]
## 현상

Run jasypt 복호화 환경변수 미지정 에러

@Test 실행 중에 error 에러 발생

>java.lang.IllegalStateException: Failed to load ApplicationContext for [WebMergedContextConfiguration@209f3887 testClass = com.githrd.figurium.order.controller.OrderControllerTest, locations = [], classes = [com.githrd.figurium.FiguriumApplication], contextInitializerClasses = [], activeProfiles = [], propertySourceDescriptors = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true"], contextCustomizers = [org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@1f, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizer@4c163e3, org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@536f2a7e, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@4bdeaabb, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@6f204a1a, org.springframework.boot.test.web.reactor.netty.DisableReactorResourceFactoryGlobalResourcesContextCustomizerFactory$DisableReactorResourceFactoryGlobalResourcesContextCustomizerCustomizer@790da477, org.springframework.boot.test.context.SpringBootTestAnnotation@59651993], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]
java.lang.IllegalStateException: Failed to load ApplicationContext for [WebMergedContextConfiguration@209f3887 testClass = com.githrd.figurium.order.controller.OrderControllerTest, locations = [], classes = [com.githrd.figurium.FiguriumApplication], contextInitializerClasses = [], activeProfiles = [], propertySourceDescriptors = [], propertySourceProperties = ["org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true"], contextCustomizers = [org.springframework.boot.test.autoconfigure.actuate.observability.ObservabilityContextCustomizerFactory$DisableObservabilityContextCustomizer@1f, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizer@4c163e3, org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@536f2a7e, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@4bdeaabb, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@6f204a1a, org.springframework.boot.test.web.reactor.netty.DisableReactorResourceFactoryGlobalResourcesContextCustomizerFactory$DisableReactorResourceFactoryGlobalResourcesContextCustomizerCustomizer@790da477, org.springframework.boot.test.context.SpringBootTestAnnotation@59651993], resourceBasePath = "src/main/webapp", contextLoader = org.springframework.boot.test.context.SpringBootContextLoader, parent = null]
at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:180)
at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:130)

<br/><br/><br/>
## 원인
위에 있는 JasyptConfig의 암호가 복호화가 되지 않아서 아래의 yml 파일안에 있는 암호화를 해석하지 못해서 class 자체가 실행이 되지 않았음. jasypt 자바 애플리케이션에서 암호화와 복호화를 쉽게 처리할 수 있도록 도와주는 라이브러리다.

```java
@Configuration
public class JasyptConfig {

    @Value("${jasypt.encryptor.password}")
    private String password;

    @Bean(name = "jasyptEncryptor")
    public StringEncryptor encrypt() {
        PooledPBEStringEncryptor encryptor = new PooledPBEStringEncryptor();

        SimpleStringPBEConfig config = new SimpleStringPBEConfig();

        config.setPassword(password);
        config.setAlgorithm("PBEWithMD5AndDES");
        config.setKeyObtentionIterations(1000);
        config.setPoolSize(1);
        config.setSaltGeneratorClassName("org.jasypt.salt.RandomSaltGenerator");
        config.setStringOutputType("base64");
        encryptor.setConfig(config);
        return encryptor;
    }
}



jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${ENCRYPT_KEY}
```

<br/><br/><br/>
## 해결책
(팀장형님이 정해놓은 복호화 환경변수 path를 지정해준다)
![image](https://github.com/user-attachments/assets/1f3ac338-cecb-4bed-a02d-df2eb4b2c164)

<br/><br/><br/>
## 결과
정상적인 실행완료

아예 실행도 안되던게 정상적으로 Test 검증을 실행시킨다.

![image](https://github.com/user-attachments/assets/90c7f9f7-dd7b-4837-a2b5-93d6ed7933b7)
